
auth.token=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

defaults.org=the-affinity
defaults.project=theaffinity-rn

defaults.url=https://sentry.io/