
auth.token=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

defaults.org=devkilat
defaults.project=react-native

defaults.url=https://sentry.io/
